import = ["~/.config/alacritty/themes/monokai_charcoal.toml"]


[colors]
draw_bold_text_with_bright_colors = true

#[colors.bright]
#black = "0x282828"
#blue = "0x458588"
#cyan = "0x689d6a"
#green = "0x98971a"
#magenta = "0xb16286"
#red = "0xcc241d"
#white = "0xa89984"
#yellow = "0xd79921"
#
#[colors.normal]
#black = "0x928374"
#blue = "0x83a598"
#cyan = "0x8ec07c"
#green = "0xb8bb26"
#magenta = "0xd3869b"
#red = "0xfb4934"
#white = "0xebdbb2"
#yellow = "0xfabd2f"
#
#[colors.primary]
#background = "0x000000"
#foreground = "0xFFFFFF"

[cursor]
style = "Underline"
unfocused_hollow = true
vi_mode_style = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "Iosevka Term"
#style = "Italic"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.padding]
x = 4
y = 1

