"
" -*- coding: utf-8 -*-
" vim: ai ts=4 sts=4 et sw=4 ft=vim
" author : Prakash [प्रकाश]
" date   : 2018-12-12
"

set nocompatible
filetype off

call plug#begin('~/.local/share/vim/bundle/')
    Plug 'ycm-core/YouCompleteMe'
    Plug 'SirVer/ultisnips'
    Plug 'lervag/vimtex'
    Plug 'scrooloose/nerdtree'
    Plug 'vim-airline/vim-airline'
    Plug 'KeitaNakamura/tex-conceal.vim'
    Plug 'tpope/vim-fugitive'
    Plug 'junegunn/gv.vim'
    Plug 'JuliaEditorSupport/julia-vim'
    Plug 'plasticboy/vim-markdown'
    Plug 'APZelos/blamer.nvim'
    Plug 'axvr/zepl.vim'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

filetype plugin indent on
syntax on

colorscheme dracula 
highlight Normal guibg=NONE ctermbg=NONE
highlight VertSplit guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE


set hidden
set tabstop=4
set shiftwidth=4
set expandtab
set cindent
set number
set relativenumber
set modeline
set modelines=5
set nowrap
set breakindent
set clipboard+=unnamedplus
set splitbelow
set splitright
set mouse=n
set foldmethod=indent
set foldlevel=1
set fileformat=unix
set nohlsearch
set incsearch
set guifont=Iosevka\ Term

let mapleader=' '


inoremap jk <esc>
inoremap jK <esc>
inoremap Jk <esc>
inoremap KJ <esc>
inoremap JK <esc>

nnoremap <A-v> <C-w>+
nnoremap <A-b> <C-w>-
nnoremap <A-m> <C-w>>
nnoremap <A-n> <C-w><

nnoremap <tab> gt
nnoremap <s-tab> gT

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

vnoremap < <gv
vnoremap > >gv

nnoremap <leader>nt :NERDTreeToggle<cr>
nnoremap <leader>nc :NERDTreeClose<cr>
nnoremap <leader>nm :NERDTreeMirror<cr>



"
" Vimtex configuration
let g:vimtex_view_method = 'zathura'
"let g:vimtex_syntax_enabled = 0
let g:vimtex_matchparen_enabled=0
"let g:matchup_override_vimtex=1
"let g:matchup_matchparen_deferred=1
let vimtex_fild_enabled=1

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

set conceallevel=1
let g:tex_conceal='abdmg'
hi Conceal ctermbg=none

let g:SuperTabDefaultCompletionType = 'jj'

" UltiSnips
let g:UltiSnipsExpandTrigger="<Tab>"
let g:UltiSnipsJumpForwardTrigger="<Tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-Tab>"
let g:UltiSnipsEditSplit="vertical"
"
"

let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#enabled = 1
"let g:airline_extensions = []
"
runtime plugin-config/functions.vim
runtime plugin-config/fzf.vim
runtime plugin-config/makrdown-conceal.vim
runtime plugin-config/makrdown-preview.vim
runtime plugin-config/nepali-map.vim
runtime plugin-config/vimwiki.vim
runtime plugin-config/vim-fugitive.vim
runtime plugin-config/zepl.vim

