#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#picom -f &
#source ~/.fehbg

source ${HOME}/.config/polybar/launch

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X


bspc config border_width         1
bspc config window_gap           5
#bspc config focused_border_color '#FAFAFA'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Matplotlib state=floating
bspc rule -a Screenkey manage=off
bspc rule -a alacritty state=floating
bspc rule -a st state=floating
bspc rule -a URxvt state=floating
bspc rule -a mpv state=floating
bspc rule -a discord state=floating
bspc rule -a Slack state=floating
bspc rule -a Deno state=tiled
bspc rule -a Toolkit state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a gksqt state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Canvas state=floating
bspc rule -a ROOT state=floating
bspc rule -a Deno state=tabbed

bspc config pointer_modifier shift
bspc config pointer_cation1 move
bspc config pointer_cation2 resize_size
bspc config pointer_cation3 resize_corner
bspc config click_to_focus true

