require("plugin.lualine")
require("plugin.nvim-lsp")
require("plugin.nvim-tree")
require("plugin.treesitter")
require("plugin.telescope")
require("plugin.luasnip")
require("plugin.vimtex")
require("plugin.cmp-nvim")
require("plugin.telekasten")
require("plugin.gitsigns")
require("plugin.neogit")
require("plugin.diffview")
require("plugin.zepl")
require("plugin.peek-nvim")
require("plugin.clipboard-image")

