require("plugin.loader").load_plugins({
  "folke/tokyonight.nvim",
  "neovim/nvim-lspconfig",
  {"nvim-telescope/telescope.nvim", dependencies= {"nvim-telescope/telescope-bibtex.nvim", "nvim-lua/plenary.nvim"}},
  {"nvim-telescope/telescope-file-browser.nvim", dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" }},
  {"nvim-treesitter/nvim-treesitter", dependencies={"nvim-treesitter/nvim-treesitter-textobjects"}},
  "lewis6991/gitsigns.nvim",
  "sindrets/diffview.nvim",
  {"TimUntersberger/neogit"},--,cfg={enable=true}},
  "nvim-lualine/lualine.nvim",
  {"nvim-neo-tree/neo-tree.nvim", dependencies = { "MunifTanjim/nui.nvim", }},
  {"L3MON4D3/LuaSnip" , event="InsertEnter", cfg={path="plugin.luasnip"}},
  { "hrsh7th/nvim-cmp", event = "InsertEnter",
    dependencies = { "hrsh7th/cmp-nvim-lsp", "hrsh7th/cmp-buffer", "hrsh7th/cmp-path", "hrsh7th/cmp-cmdline","hrsh7th/cmp-calc", },
  },
  {"lervag/vimtex", ft="tex"},
  --"renerocksai/telekasten.nvim",
  { "toppair/peek.nvim", event = {"VeryLazy"}, build = 'deno task --quiet build:fast', },
  --{"axvr/zepl.vim"},
  --{"JuliaEditorSupport/julia-vim",ft={'julia'}},
  {dir="~/.Rough/nvim/clipboard-image.nvim",cfg={path="plugin.clipboard-image"}},
  --{dir="~/.Rough/nvim/tepl",cfg={path="plugin.tepl"}},
  "pranphy/nevl.nvim",
  "folke/zen-mode.nvim",
  {'kaarmu/typst.vim', ft = {'typst'}},
  {"epwalsh/obsidian.nvim", version = "*", lazy = true, ft = "markdown"},
  {"rcarriga/nvim-dap-ui", dependencies = {"theHamsta/nvim-dap-virtual-text","nvim-neotest/nvim-nio"}},
  {"mfussenegger/nvim-dap", cfg={path="plugin.nvim-dap"}},
  { 'MeanderingProgrammer/markdown.nvim', name = 'render-markdown',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, cfg={enable=false}, 
  },
 "numToStr/FTerm.nvim",
 {"Exafunction/codeium.vim"},

})

