#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 ft=sh

# author : Prakash [प्रकाश]
# date   : 2022-01-17 16:42

# autput: switches AUdio ouTPUT currently available in system.

tell="notify-send"
menu="dmenu -i"
[[ $- != *i* ]] && menu="dmenu -i" || menu="fzf"


function get_menu()
{
    local -n div=${1}
    arraylen=${#div[@]}
    for (( i=0; i<${arraylen}; i++ ));
    do
        name=$(echo ${div[${i}]} | awk '{print $2}' | sed -re 's/alsa_output.[a-z]{3}-(.*)/\1/' | sed -re 's/[0-9_\.]*//g' )
        id=$(echo ${div[${i}]} | awk '{print $1}' )
        echo "${id} ${name}"
    done
}

mapfile -t dvcs < <(pactl list short sinks)

device=$(get_menu dvcs | ${menu} )
id=$(echo ${device} | egrep -o '^[0-9]+' )


pactl set-default-sink ${id}


${tell} "${device}: set as default"

