#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 ft=sh

# author : Prakash [प्रकाश]
# date   : 2020-07-21 18:47

FILE=${1:?No file}
VIEW=${2}
CONVERT=${3}
DESTDIR=${4:-""}

OPDIR=$(mktemp -d -t latex_view-XXXXXXXXXX)
mkdir -p ${OPDIR}


FILENAME=$(basename -- "$FILE")
FILEPATH="${FILE%$FILENAME}"
EXTENSION="${FILENAME##*.}"
FILEBASE="${FILENAME%.*}"

DESTDIR=${DESTDIR:-${FILEPATH}}
LATEXPATH=${OPDIR}/${FILEBASE}.tex
PDFPATH=${OPDIR}/${FILEBASE}.pdf
PNGPATH=${OPDIR}/${FILEBASE}.png


TIKZCONTENT=$(<${FILE})

#echo "${TIKZCONTENT}"

cat > ${LATEXPATH} << EOF
\documentclass[10pt]{standalone}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{pgfplots}
\usepackage{tikz}
\usepackage{tikz-feynman}
\usetikzlibrary{
    arrows.meta,
    backgrounds,
    calc,
    calligraphy,
    decorations.fractals,
    decorations.markings,
    decorations.pathmorphing,
    decorations.pathreplacing,
    decorations.shapes,
    decorations.text,
    fit,
    fillbetween,
    intersections,
    math,
    matrix,
    mindmap,
    positioning,
    quotes,
    shapes
}
\usepgfplotslibrary{
    groupplots%
}
\begin{document}
    ${TIKZCONTENT}
\end{document}
EOF


#cat ${LATEXPATH}

[[ "${CONVERT}" == "yes" ]]  && lualatex --shell-escape  -output-directory=${OPDIR} ${LATEXPATH}

if [[ -x $(which convert) ]]
then
    cmd="convert -density 150 -transparent white ${PDFPATH} ${PNGPATH}"
    #cmd="pdftoppm ${PDFPATH} ${OPDIR}/${FILENAME} -png -f 1 -singlefile"
    echo ${cmd}
    ${cmd}
fi

[[ "${VIEW}" == "yes" ]] && zathura ${PDFPATH}

[[ ${DESTDIR} == "" ]] || cp ${PNGPATH} ${DESTDIR}  || echo "Copying ${PNGPATH} failed to ${DESTDIR}"


