require('vim._core.ui2').enable({
  enable = true,
  msg = {
    targets = {
      [''] = 'cmd',
      empty = 'cmd',
      bufwrite = 'msg',
      confirm = 'cmd',
      emsg = 'msg',
      echo = 'pager',
      echomsg = 'msg',
      echoerr = 'msg',
      completion = 'cmd',
      list_cmd = 'pager',
      lua_error = 'msg',
      lua_print = 'pager',
      progress = 'msg',
      rpc_error = 'msg',
      quickfix = 'msg',
      search_cmd = 'cmd',
      search_count = 'cmd',
      shell_cmd = 'pager',
      shell_err = 'pager',
      shell_out = 'pager',
      shell_ret = 'msg',
      undo = 'msg',
      verbose = 'pager',
      wildlist = 'cmd',
      wmsg = 'msg',
      typed_cmd = 'cmd',
    },
    cmd = {
      height = 0.5,
    },
    dialog = {
      height = 0.5,
    },
    msg = {
      height = 0.5,
      timeout = 4000,
    },
    pager = {
      height = 3,
    },
  },
})
