#!/usr/bin/env bash
# vim: ai ts=4 sts=4 et sw=4 ft=sh

function SlacDB()
{
    host="mysql-node03.slac.stanford.edu"
    user='rd_exo_u'
    password='ex#P45$m2q'
    db="rd_exo"


    slacdb="/opt/lampp/bin/mysql -u"${user}" -p'"${password}"' -h${host} -D${db}"
    echo "executing "$slacdb
    $slacdb
}

function CopySlac()
{
    BASE=/nfs/slac/g/exo/pgphoton

    declare -A locations=(\
        ["PreProc"]="${BASE}/RootOutDir/PreProc"\
        ["ignore_plot"]="${BASE}/Sabthok/PhaseI/ignore_plot"\
        ["workspaces"]="${BASE}/Sabthok/PhaseI/FitPlot/MuonCut/workspaces"\
        ["PhaseII"]="${BASE}/Sabthok/PhaseII"\
        ["recon"]="/nfs/slac/g/exo_data3/exo_data/data/WIPP/recon"\
        ['LightMap']="${BASE}/Sabthok/LightMap"\
        ["GitRepos"]="${BASE}/GitRepos"\
        ["other"]="${BASE}"\
        ["home"]="~pgphoton"

    )

    from=${locations[$1]}

    fname=$2
    to=$3

    if [[ "$2" == '' ]]
    then
        fname='*'
    fi

    if [[ "$3" == '' ]]
    then
        to="."
    fi
    cmd="scp -r pgphoton@rhel6-64.slac.stanford.edu:${from}/${fname} ${to}"
    echo $cmd
    $cmd
    echo "Done copying "
}

function LJlab()
{
    port=${2}
    if [[ "${port}" == '' ]]; then
        port="8181"
    fi

    fname=$(mktemp)
    jupyter lab --port=${port}> $fname 2>&1 &
    token=''
    while [[ "$token" == '' ]]
    do
        token=$(cat $fname | grep "localhost:${port}")
    done

    echo "Token :"${token}
}

function RootLs()
{
    fname=$1
    echo " now excuting the command"
    python -c 'import ROOT; TT=ROOT.TFile("'$fname'"); dt = TT.Get("dataTree"); dt.ls()'
}

function RepString()
{   
    if [[ ${1} == "-h" ]]
    then
        echo "RepString <path_to_files> <from_regex> <to_regex> <filewildcard>"
        echo "   replaces string in all file matching <filewildcard>  for  all"
        echo "   occurances of <from_regex> to <to_regex>. Use with caution as"
        echo "   it might damage files"
    fi

    path=$1
    from=$2
    to=$3
    wildcard=$4

    cmd="find "${path}" -name '"${wildcard}"' -exec sed -i -e 's#"${from}"#"${to}"#g' {} ;"
    echo $cmd
    exec $cmd;
}

function PyCalc()
{
    python -c "print("$@")"
}

function jc()
{
    command='julia -E  "'$@'"'
    echo ${command}
    julia -E "${@}"
}


function PyVersion()
{
    for pac in $@
    do
        python -c 'import '$pac' as pkg; print("'$pac' :: {} ".format(pkg.__version__))'
    done
}

function PipShow()
{
    pip="pip"$1
    echo "Listing packages for "$pip
    $pip list --format freeze|awk -F = {'print $1'}| xargs $pip show | grep -E 'Location:|Name:' | cut -d ' ' -f 2 | paste -d ' ' - - | awk '{print $2 "/" tolower($1)}' | xargs du -sh 2> /dev/null|sort -h
}


# Mount my disks by name "
function Mount()
{
    drive=$@
    for dr in $drive
    do
        if  [[ "${dr,,}" == "study"  ]]; then
            udisksctl mount -b  /dev/sda3
        elif [[ "${dr,,}" == "backup" ]]; then 
            udisksctl mount -b  /dev/sda4
        else
            printf "Unknown parameter: $drive \n\tusage :: Mount disk_label1 [,disk_label2, ... ]\n"
        fi
    done
}


# UnMount my disks by name "
function UnMount()
{
    drive=$@
    for dr in $drive
    do
        if  [[ "${dr,,}" == "study"  ]]; then
            udisksctl unmount -b  /dev/sda3
        elif [[ "${dr,,}" == "backup" ]]; then 
            udisksctl unmount -b  /dev/sda4
        else
            printf "Unknown parameter(s) $drive \n\t usage :: UnMount disk_label1 [,disk_label2, ... ]\n"
        fi
    done
}

function CreateGitRepo()
{
    name=$1
    desc=$2
    command='curl -u pranphy https://api.github.com/user/repos -d {"name":"'$name'"}'
    echo $command
    $command
}

function DelExcept()
{ cmd="find . -type f "
    for pattern in "$@"; do
        cmd=$cmd"-not -name '"$pattern"' "
    done
    #cmd=$cmd" | parallel rm"
    cmd=$cmd" -exec mv {} .Trash +"
    echo $cmd
    $cmd

}

function MakeGrayscale()
{
    infil=${1}
    outfil=${2}
    gs \
    -sOutputFile=${outfil} \
    -sDEVICE=pdfwrite \
    -sColorConversionStrategy=Gray \
    -dProcessColorModel=/DeviceGray \
    -dCompatibilityLevel=1.4 \
    -dNOPAUSE \
    -dBATCH \
    ${infil}
}

function FetchLyrics()
{
    artist=${1}
    title=${2}
    curl -s --get "https://makeitpersonal.co/lyrics" --data-urlencode "artist=$artist" --data-urlencode "title=$title"
}


function ResetLocal()
{
    FNAME=${1}
    rm ${FNAME}
    git checkout ${FNAME}
}


function MakeDiary()
{
    path=$1
    date=`date +%Y-%m-%d`
    date_AD=`date +%Y.%m.%d`
    date_BS=`nepaliconv -bs ${date_AD} -f 'y M d W' -u` 
    touch $path/$date.md
    
cat > ${path}/${date}.md<< EOF
---
मिति: ${date_BS} [${date}]
लेखक: प्रकाश [Prakash]
---
[//]: # (केही टिप्पणी लेख्नुहोस्)
EOF
}



function JekyllPost()
{
    if [[ $1 == "-h" ]]
    then
        echo "Creates Jekyll post"
        echo "JekyllPost <path> <title space separated>"
        return 
    fi
    path=$1
    title=$2
    
    title_slug=$(echo "${title}" | sed 's/\s\+/-/g' | tr '[:upper:]' '[:lower:]' )
    
    date=`date +%Y-%m-%d`
    date_AD=`date +%Y.%m.%d`
    date_BS=`nepaliconv -bs ${date_AD} -f 'y M d W' -u` 
    filepath=${path}/${date}-${title_slug}.md
    
cat > ${filepath}<< EOF
---
title: ${title}
author: प्रकाश
date : ${date} 
मिति : ${date_BS}
tags :
categories:
description: 
---

[//]: # (केही टिप्पणी लेख्नुहोस्)
EOF
echo "${filepath} created"
}
 

function MakeHW()
{
    CRN=${1}
    SUBJECT=${2}
    HWN=${3}


    HWDIR=HW${HWN}

    echo " Making files in " ${HWDIR}

    mkdir ${HWDIR}

cat > ${HWDIR}/PHYS${CRN}HW${HWN}.tex << EOF
% Autohr : Prakash Gautam
% Date   : `date +%d-%m-%Y` `date +%H:%M:%S`
\documentclass[10pt]{article}
\usepackage[margin=22mm]{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{physics}
\usepackage{pgmath}
%
\newcommand{\curdir}{.}
\newcommand\numberthis{\addtocounter{equation}{1}\tag{\theequation}}
\author{Prakash Gautam}
\title{PHYS ${CRN}: ${SUBJECT}\\\\ {\large Homework \#${HWN}}}
%\title{New title}

\begin{document}
    \maketitle
    \input{PHYS${CRN}HW${HWN}_Done.tex}
\end{document}
EOF

cat > ${HWDIR}/PHYS${CRN}HW${HWN}_Done.tex << EOF
\begin{questions}
\question [Book 1.1] %
    %
\end{questions}
EOF
}

function TimeAv()
{
    rm -f /tmp/mtime.$$

    for x in {1..10}
    do
      /usr/bin/time -f "real %e user %U sys %S" -a -o /tmp/mtime.$$ $@
      tail -1 /tmp/mtime.$$
    done

    awk '{ et += $2; ut += $4; st += $6; count++ } END {  printf "Average:\nreal %.3f user %.3f sys %.3f\n", et/count, ut/count, st/count }' /tmp/mtime.$$
}

function fed()
{
    if [[ ${1} == "-h"  || ${1} == "--help" ]]
    then
        echo "Finds a file with fzf and edits with nvim "
    fi

    given_path="$(readlink -f $(fzf))"
    root_path="${given_path}"
    if [[ -d ${root_path} ]]
    then
        cd ${root_path}
    else
        found=false
        while [[ ("${found}" == "false") && ("${root_path}" != "") ]]
        do
            root_path="$(dirname -- "$(readlink -f -- "$root_path")")"
            if [[ -d "${root_path}"/.git ]]
            then
                found=true
                pushd . &> /dev/null
                cd "${root_path}"
                nvim "${given_path}"
                popd &> /dev/null
                return 0
            fi
        done
    fi
}

